[project]
name = 'eco-contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.public-ledger]
path = 'contracts/public-ledger.clar'
clarity_version = 2
epoch = 2.5

[contracts.reputation-system]
path = 'contracts/reputation-system.clar'
clarity_version = 3
epoch = 3.0

[contracts.token-reward]
path = 'contracts/token-reward.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
